root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/falcon"
  cmd = "go build -o ./tmp/falcon ./cmd/falcon"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "docs", "examples", ".git"]
  exclude_file = ["*.md", "*.json", "*.yaml", "*.yml", "*.txt", "*.log", "Dockerfile*", "docker-compose*", "*.env", "*.toml", "*.sh", "*.sql", "*.png", "*.jpg", "*.jpeg", "*.gif", "*.svg", "*.ico", "*.pdf", "*.zip", "*.tar", "*.gz"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["cmd", "internal", "pkg"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "500ms"
  log = "tmp/build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = ["mkdir -p tmp"]
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true