#!/bin/bash

# Script to show available API routes in the Go Falcon gateway

echo "=== Go Falcon API Routes ==="
echo ""

echo "🔐 Authentication Routes (via /api/auth):"
echo "  GET  /api/auth/eve/login         - Initiate EVE SSO login"
echo "  GET  /api/auth/eve/callback      - OAuth2 callback handler"
echo "  GET  /api/auth/eve/verify        - Verify JWT token"
echo "  POST /api/auth/eve/refresh       - Refresh access tokens"
echo "  POST /api/auth/eve/token         - Exchange EVE token for JWT (mobile)"
echo "  GET  /api/auth/status            - Quick auth status check"
echo "  GET  /api/auth/user              - Get current user info"
echo "  POST /api/auth/logout            - Clear auth cookie"
echo "  GET  /api/auth/profile           - Get full user profile (requires auth)"
echo "  POST /api/auth/profile/refresh   - Refresh profile from ESI (requires auth)"
echo "  GET  /api/auth/profile/public    - Get public profile by ID"
echo ""

echo "👥 Groups Routes (via /api):"
echo "  GET  /api/groups                 - List all groups with membership status"
echo "  POST /api/groups                 - Create a new custom group (admin only)"
echo "  PUT  /api/groups/{id}            - Update an existing group (admin only)"
echo "  DELETE /api/groups/{id}          - Delete a custom group (admin only)"
echo ""

echo "👤 Group Membership Routes:"
echo "  GET  /api/groups/{id}/members    - List all members of a group (admin only)"
echo "  POST /api/groups/{id}/members    - Add a member to a group (admin only)"
echo "  DELETE /api/groups/{id}/members/{characterID} - Remove member (admin only)"
echo ""

echo "🛡️ Permission Routes:"
echo "  GET  /api/permissions/check?resource={resource}&action={action} - Check permission"
echo "  GET  /api/permissions/user       - Get user's complete permission matrix"
echo ""

echo "⚙️ Development Routes (via /api/dev):"
echo "  GET  /api/dev/health             - Development module health check"
echo "  GET  /api/dev/sde/*              - SDE data access endpoints"
echo "  GET  /api/dev/esi/*              - ESI testing endpoints"
echo ""

echo "👥 Users Routes (via /api/users):"
echo "  GET  /api/users/health           - Users module health check"
echo ""

echo "📬 Notifications Routes (via /api/notifications):"
echo "  GET  /api/notifications/health   - Notifications module health check"
echo ""

echo "⏰ Scheduler Routes (via /api/scheduler):"
echo "  GET  /api/scheduler/health       - Scheduler module health check"
echo "  GET  /api/scheduler/tasks        - List all scheduled tasks (requires auth)"
echo "  POST /api/scheduler/tasks        - Create new task (admin only)"
echo "  GET  /api/scheduler/stats        - Get scheduler statistics (admin only)"
echo ""

echo "🏥 System Routes:"
echo "  GET  /health                     - Gateway health check with version info"
echo ""

echo "=== Default Groups Available ==="
echo ""
echo "🔓 guest         - Unauthenticated users (public read access)"
echo "🔐 full          - Authenticated EVE users (standard permissions)"
echo "🏢 corporate     - Corporation/alliance members (enhanced access)"
echo "👨‍💼 administrators - System administrators (management privileges)"
echo "⚡ super_admin    - Ultimate authority (wildcard permissions)"
echo ""

echo "=== Permission Resources ==="
echo ""
echo "🌐 public        - Public resources"
echo "👤 user          - User-specific resources"
echo "📝 profile       - User profile data"
echo "🏢 corporation   - Corporation-specific resources"
echo "🤝 alliance      - Alliance-specific resources"
echo "👥 groups        - Group management"
echo "🔧 system        - System administration"
echo "🛠️ admin         - Administrative functions"
echo ""

echo "=== Permission Actions ==="
echo ""
echo "📖 read          - View/retrieve data"
echo "✏️ write         - Modify/create data"
echo "🗑️ delete        - Remove data"
echo "⚙️ admin         - Administrative control"
echo "⭐ *             - Wildcard (all actions)"
echo ""

echo "=== Example Usage ==="
echo ""
echo "# Check if user can write to user resources:"
echo "GET /api/permissions/check?resource=user&action=write"
echo ""
echo "# Get all available groups:"
echo "GET /api/groups"
echo ""
echo "# Create a new group (admin only):"
echo "POST /api/groups"
echo "Content-Type: application/json"
echo "Authorization: Bearer <jwt_token>"
echo '{"name": "beta-testers", "description": "Beta testing group", "permissions": {"user": ["read", "write"]}}'
echo ""

echo "=== Authentication Examples ==="
echo ""
echo "# Web Authentication Flow:"
echo "1. GET  /api/auth/eve/login      - Get EVE SSO URL"
echo "2. [User authenticates with EVE Online]"
echo "3. GET  /api/auth/eve/callback   - Process callback (sets cookie)"
echo "4. GET  /api/auth/user           - Get user info from cookie"
echo ""
echo "# Mobile Authentication Flow:"
echo "1. [App handles EVE SSO directly]"
echo "2. POST /api/auth/eve/token      - Exchange EVE token for JWT"
echo "3. Use 'Authorization: Bearer <jwt>' header for API calls"
echo ""

echo "=== Configuration Environment Variables ==="
echo ""
echo "# Required for EVE SSO:"
echo "EVE_CLIENT_ID=your_client_id"
echo "EVE_CLIENT_SECRET=your_client_secret"
echo "JWT_SECRET=your_jwt_secret"
echo ""
echo "# Optional:"
echo "API_PREFIX=api                   # API prefix (default: 'api')"
echo "SUPER_ADMIN_CHARACTER_ID=123456789  # Super admin character ID"
echo "GROUPS_CACHE_TTL=300            # Permission cache TTL (default: 300)"
echo "ENABLED_CORPORATION_IDS=123,456,789  # Enabled corp IDs for corporate group"
echo "ENABLED_ALLIANCE_IDS=123,456     # Enabled alliance IDs for corporate group"
echo ""

echo "=== Ready to Use! ==="
echo ""
echo "The groups module is now fully integrated and ready for use."
echo "Check the comprehensive documentation in internal/groups/README.md"
echo "for detailed API references and integration examples."